### ISSUE TITLE
Getting user profile from b2c directory

### ISSUE THREAD

**Issue by ppopadiyn** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#13]
Assuming the user has logged in, is there a way to obtain their profile information with hello.js? Something like:

```
hello(network.adB2CSignInSignUp).api('/me').then(function (r) {
	console.log(r);
});
```

Or I need to work directly with the azure graphAPI?

Thanks

**Comment by gsacavdm** [comment]
You can access whatever information about the user you configure to be sent in the id_token, see [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-custom-attr#use-a-custom-attribute-in-your-sign-up-policy) instructions which indicate how to configure what claims get sent. The article talks about custom claims but the same steps apply for built-in claims.

Alternatively, if you really want to query the graph, the only option at this time is by having your SPA call an API which would in turn [call the Graph using client credentials](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet) and asking for information about a specific user since /me does not work for the client credentials flow.
