### ISSUE TITLE
This application does not have sufficient permissions

### ISSUE THREAD

**Issue by thdotnet** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#16]
I've cloned this repository and after I've replaced the settings with my Azure AD B2C settings, I'm getting the following error:

_This application does not have sufficient permissions against this web resource to perform the operation._

Any tips on what is wrong?

**Comment by thdotnet** [comment]
I've noticed some differences in the URL that prompts for the username and password comparing with the url generated by MSAL.

First difference:

MSAL: 
https://login.microsoftonline.com/te/

Hello:
https://login.microsoftonline.com/tfp/


Second difference:

MSAL: 
&response_type=id_token

Hello:
&response_type=token%20id_token

Third difference:

MSAL:
scope=https%3A%2F%2Fmytenantonmicrosoft.com%2Fmyapp%2Fdemo.read%20openid%20profile

Hello:
&scope=openid%20https://mytenantonmicrosoft.com/myapp/demo.read

If I change to the same pattern that MSAL uses, then I can redirect to the sample project after typing the username and password, otherwise, I'm getting the error above. Is that correct?

**Comment by parakhj** [comment]
Good investigation! 

First difference: 
The difference between the two URL's don't matter. Just two different URL's that both work

Second difference:
One returns an id_token, and the second returns both an id_token and an access_token. (This is the problem as explained below)

Third difference: The profile scope doesn't make a difference, so they're essentially the same.

The request is failing because you don't have the permissions configured properly for the access token to be sent, and since you don't ask for an access token in the MSAL request, the request works just fine (and returns an id_token). 

Access tokens are intended to be used to access API's. If you don't have an API, don't worry about the "token" response_type. If you do have an API, check out this [blog post](https://azure.microsoft.com/en-us/blog/azure-ad-b2c-access-tokens-now-in-public-preview/) to configure the permissions correctly. For more detailed instructions, [read this document](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens).

**Comment by thdotnet** [comment]
Thanks parakhj, I'll read the blog post and see if I can proceed with that. I'll update this thread soon.

**Comment by jfbloom22** [comment]
@parakhj thanks for linking to the blog post!  I followed that and everything started working well for me.  The key was setting my scope to something similar to their example: “https://B2CBlog.onmicrosoft.com/notes/read”.

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp
