### ISSUE TITLE
Can't set response_type=code to request refresh_token (offline_access)

### ISSUE THREAD

**Issue by longxuanho** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#21]
~~~~
hello.init({
            adB2CSignInSignUp: applicationId,
            adB2CEditProfile: applicationId
        }, {
            redirect_uri: '../redirect.html',
            scope: 'openid ' + scope,
            response_type: 'token id_token'
        });
~~~~
In this snippet above I can't set response_type = code to perform explicit Oauth flow (to get refresh_token for hello.js). What should I do?

The token retrieved by this example will expire in 1 hour (by default) and can't be refreshed. How can I refresh the token in silent?

**Comment by parakhj** [comment]
You cannot obtain refresh tokens when you are using javascript web apps (which use implicit flows and implicit flows by protocol definition do not grant refresh tokens).

You should rely on your cookies and periodically do an iframe call to periodically get a new access token.

**Comment by longxuanho** [comment]
Did you mean that I had to check access token periodically and call method ```hello(network).login({display: none})``` manually, like this:
```javascript
setInterval(tryRefreshToken, 100000);
// ...
function tryRefreshToken() {
  var session = hello(network).getAuthResponse(network);
  var currentTime = (new Date()).getTime() / 1000;
  
  if (session && session.expires && session.expires_in 
  && (session.expires - currentTime) < (session.expires_in / 2)) {
    console.log('refresh token...')
    hello(network).login({ display: 'none' }, authLog)
  }
}
```
The new token is renewed only when I open the web app. How can I do this in background (to keep users logged in even if they close the web app for days)?

Using Auth0 instead of B2C allow me to obtain refresh_token via javascript jQuery ajax call as mentioned in this post: ```https://auth0.com/docs/tokens/refresh-token/current```.

**Comment by jmprieur** [comment]
@longxuanho, you might want to use [msal.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) instead of hello.js, as msal.js handles (between other things) the refresh token.  You could have a look at the following sample which uses msal.js: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp. 
You might want to replace the version of msal.js in that sample by the version in the [dev] branch(https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/out/msal.js) as we have fixed a number of issues (we'll release a new version of msal.js soon which should be close to that one)

**Comment by longxuanho** [comment]
Thank you for the information.
