### ISSUE TITLE
I think I don't understand what SPA means

### ISSUE THREAD

**Issue by momalek** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#6]
I really thought that I understood what a SPA means but it seems I don't if this application can be called as a SPA. My understanding for a SPA is that I never get redirected from that single application to any other application. So the user experience is no altered nor changed. But from what I see in this sample it is implementing a popup window that again redirects the user. I think the title should e changed as this is not a real SPA.

**Comment by rajanikanthr** [comment]
changed hellojs displaytype from `popup` to `page`, so for login page gets redirected to Azure AD B2C instead of popup and after successful authentication it will redirect to the SPA app with auth state. Subsequent operations like GET and POST calls to TaskService and silent renew happens from the SPA app.  

Having a separate login page or redirecting to another provider like Azure AD B2C is allowed in SPA apps though it doesn't abide by the literal definition of SPA.
